### PR TITLE
Remove pytz dependency

### PR DESCRIPTION
**Pull request by aclatham**
Pytz is not included in docker pip install causing an error when running Lambda auditor. This PR removes the dependency.

### CODE REVIEW

**Comment by jonrau1** [comment]
LGTM. Can you also add a version of this to the GovCloud Auditors? Should not need much change other than the Partition information from `aws` to `aws-gov`

**Comment by jonrau1** [comment]
SAA. New SNS check looks good to go just needs a GovCloud companion.

Once I merge into Master I will revisit the new additions and add the Compliance.RelatedRequirements information to them

**Comment by jonrau1** [comment]
Also need `sns:GetTopicAttributes` added to the three policies.

**Comment by aclatham** [comment]
I believe just the IAM policy was missing `sns:GetTopicAttributes` but let me know if that's incorrect @jonrau1

**Comment by jonrau1** [comment]
@aclatham just checked your master, everything LGTM and is ready to 🚢 🚢 🚢. Are there any other commits you want to push to this PR before I merge it?

**Comment by pbrazil03** [comment]
I have one more before merge

**Comment by jonrau1** [comment]
@pbrazil03 LGTM. Good catch on the check numbering. Will merge in a bit.

**Comment by aclatham** [comment]
Alright that should be the last one

**Pull request merged**
