### PR TITLE
Replace of package requests with urllib3. This replacement eliminates…

### PR DESCRIPTION
**Pull request by bhargavak37**
Replace of package requests with **urllib3**. This replacement eliminates the pain of importing this layer as an ARN from **Klayers** and removes the parameter **Python3RequestsLayer**

**urllib3** is available out of box at Lambda

### Changes done:
  At the these templates present at the below paths replaced the import of requests with urllib3 and further make an http POST request using urllib3

- add-ons\electriceye-chatops\cloudformation\ElectricEye_ChatOps_CFN.yml

- add-ons\electriceye-chatops\microsoft-teams\cloudformation\ElectricEye_ChatOps_Teams_CFN.yml

-  add-ons\electriceye-pagerduty-integration\cloudformation\ElectricEye_Pagerduty_CFN.yml

At these raw source code files at below paths replaced the import of **requests** with **urllib3** and further make an http POST request using urllib3

- add-ons\electriceye-chatops\raw-source\ElectricEye-ChatOps.py

- add-ons\electriceye-pagerduty-integration\raw-source\ElectricEye-to-Pagerduty.py

 
Have tested the making of POST request using urllib3. 
@jonrau1 Requesting your review on this PR

### CODE REVIEW

**Comment by bhargavak37** [comment]
@jo

**Comment by jonrau1** [comment]
Hi @bhargavak37 can you also remove the Variables from the Terraform file?

**Comment by bhargavak37** [comment]
@jonrau1  , do you mean at these places . Yes will do. Should I raise a new PR or could I commit to the same branch 

https://github.com/jonrau1/ElectricEye/tree/master/add-ons/electriceye-chatops/terraform
https://github.com/jonrau1/ElectricEye/tree/master/add-ons/electriceye-pagerduty-integration/terraform

**Comment by jonrau1** [comment]
You can commit to the same branch, thanks. Just want to maintain consistency across the IAC options

**Comment by bhargavak37** [comment]
The event pattern wasn't updated. So corrected the event pattern at main.tf at 

  add-ons\electriceye-pagerduty-integration\terraform\main.tf
  add-ons\electriceye-chatops\terraform\main.tf
  add-ons\electriceye-chatops\microsoft-teams\terraform\main.tf


Removed the variables from variables.tf and main.tf at 

  add-ons\electriceye-chatops\microsoft-teams\terraform
  add-ons\electriceye-chatops\terraform
  add-ons\electriceye-pagerduty-integration\terraform

**Pull request merged**
